{% set name = "ros-roslz4" %}
{% set version = "1.14.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ros-gbp/ros_comm-release/archive/release/melodic/roslz4/{{ version }}.tar.gz
  fn: ros-roslz4-{{ version }}.tar.gz
  sha256: dadf5c7b77d73c30ae362fc3851db8403bf3c1f36cb771918df86f6a015945b4
  patches:
    - fix_python_libs.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('ros-roslz4') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
  host:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - ros-cpp-common
    - catkin_pkg
    - python
    - lz4-c
    - ros-catkin
  run:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - ros-cpp-common
    - python
    - lz4-c

test:
  requires:
    - rospkg
  commands:
    - export ROS_ROOT=$PREFIX && python -c "import rospkg;s = rospkg.RosPack();ret = s.get_path('roslz4');print(ret)"

about:
  home: https://wiki.ros.org
  summary: |
    A Python and C++ implementation of the LZ4 streaming format.
  description: |
    A Python and C++ implementation of the LZ4 streaming format. Large data
    streams are split into blocks which are compressed using the very fast LZ4
    compression algorithm.
  license: BSD-3-Clause
  license_file: include/roslz4/lz4s.h

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - seanyen
